### Create Books
POST http://localhost:4004/browse/Books HTTP/1.1
Content-Type: application/json

{
    "title": "Test",
    "description": "Test Desc",
    "author_ID" : "c1e701bd-eabc-4355-9688-338f9cb709e8",
    "stock" : 100,
    "price" : "120.00",
    "Currency_code" : "INR"
}

### Get Books
GET http://localhost:4004/browse/Books HTTP/1.1
Content-Type: application/json
